services:
  - type: web
    name: crypto-history
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server_history:app
    plan: free
    autoDeploy: true
